CREATE DATABASE MinesPvP;
GO
USE MinesPvP;
GO

CREATE TABLE [Users] (
  UserId INT IDENTITY(1,1) PRIMARY KEY,
  Username NVARCHAR(100) NOT NULL UNIQUE,
  PasswordHash NVARCHAR(256) NOT NULL
);

CREATE TABLE [Rooms] (
  RoomId NVARCHAR(50) PRIMARY KEY,
  Player1Id INT NOT NULL,
  Player2Id INT NULL,
  CreateDay DATETIME NOT NULL DEFAULT GETDATE(),
  FOREIGN KEY (Player1Id) REFERENCES Users(UserId),
  FOREIGN KEY (Player2Id) REFERENCES Users(UserId)
);

CREATE TABLE [MatchHistories] (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  RoomId NVARCHAR(50) NOT NULL,
  Result NVARCHAR(50) NOT NULL, -- e.g. "P1", "P2"
  MatchCreateDay DATETIME NOT NULL DEFAULT GETDATE(),
  FOREIGN KEY (RoomId) REFERENCES Rooms(RoomId)
);

SELECT * FROM Users
SELECT * FROM Rooms
SELECT * FROM MatchHistories